spring.application.name=prueba
server.port=${PORT:8080}

# Configuración exclusiva del Starter de Spring Cloud GCP SQL
spring.cloud.gcp.sql.database-name=${DB_NAME:prueba}
spring.cloud.gcp.sql.instance-connection-name=${DB_INSTANCE_CONNECTION_NAME}

# Credenciales de acceso
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# En Spring Boot 3.4+ es mejor usar el dialecto moderno para MySQL 8+
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
