spring.application.name=prueba
server.port=${PORT:8080}

# URL manual adaptada con tus variables de Cloud Run y parámetros SSL obligatorios
spring.datasource.url=jdbc:mysql://google/${DB_NAME}?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=true&requireSSL=true&verifyServerCertificate=false
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Credenciales dinámicas (Usan los valores del panel web de Cloud Run)
spring.datasource.username=${DB_USER:gem}
spring.datasource.password=${DB_PASS:root}

# Configuración de Hibernate idéntica a tu ejemplo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
